version: '2'
services:
    postgresql:
        image: uwitech/postgresql
        # volumes:
        #     - ~/volumes/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=dhis
            - POSTGRES_DB=dhis2
            - POSTGRES_PASSWORD=dhis
        ports:
            - 5432:5432
